### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by williamgl3** [SistemasTecTlaxiaco/actividad-1-infografia-williamgl3#1]
https://drive.google.com/file/d/1dC6xK-6Z3X8_s7_tBlDJE8wA5Q655Nvs/view?usp=sharing
![Infografía FS](https://github.com/user-attachments/assets/b4c15224-322c-4e79-85ba-422c472954e1)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by AricelCastro** [comment]
Calificacion  19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
